### ISSUE TITLE
Alternative Download source

### ISSUE THREAD

**Issue by IzzySoft** [manimaul/mxtide-android#13]
First thanks for providing your app as open source! Could you also make it available outside the "walled garden" of Google Play – e.g. by attaching the APK to `releases/`, or even bringing it to [F-Droid](https://f-droid.org/)? Also, what license is it using?

Thanks in advance!

**Comment by manimaul** [comment]
@IzzySoft the license is GPLv3 which is linked to from the README.md
https://github.com/manimaul/mxtide-android/blob/master/gpl-3.0.md

Yes, APKs can be published to releases based on tags. ( see #16 )

**Comment by IzzySoft** [comment]
Thanks @manimaul – I've subscribed to the linked issue to get a ping when it's ready.
