### ISSUE TITLE
CICD Tests and Artifacts

### ISSUE THREAD

**Issue by manimaul** [manimaul/mxtide-android#16]
Setup CICD pipeline that runs tests and publishes build artifact(s) (APKs) to Github releases based on tags.

- Tests should run on every branch
- PRs should require passing tests
- Tags should publish APK artifact(s)

Links: #15

**Comment by manimaul** [comment]
All future tags will have a corresponding release APK. 

For example tag 4.1-vcx-SNAPSHOT - https://github.com/manimaul/mxtide-android/releases/tag/4.1-vcx-SNAPSHOT

Note that the release apk is unsigned and universal. So, it will be quite a bit larger than the APKs available on Google Play since it includes all architectures and resource buckets.

**Comment by IzzySoft** [comment]
Thanks, but: are unsigned APKs suitable for end-users? Aren't they posing a security risk (anyone could build a "tampered update")?

**Comment by manimaul** [comment]
> Thanks, but: are unsigned APKs suitable for end-users? Aren't they posing a security risk (anyone could build a "tampered update")?

Any APK you download and side-load is a security risk whether it's signed or not. 

I don't really want to sign APKs using a real key via Github automation. For signed, device optimized APKs there's always https://play.google.com/store/apps/details?id=com.mxmariner.tides . Google Play is the official distribution channel for MX Tides and I don't really want to support other channels.

I suppose that APKs could be signed with an alternative key. But, I need to understand what the goal would be.

**Comment by IzzySoft** [comment]
The goal would be to provide those not using Google with an as-safe-as-possible way to install and update the app. Your signature on the APK would make it much harder for someone to provide a tampered APK and have an unaware user update with that.

A signed APK would enable me to provide an easy way by adding it to [my repo](https://apt.izzysoft.de/fdroid) (updates would be available there within 24h of your adding the signed APK to a new tag – and users could take the F-Droid client to stay informed/updated).

Another approach would be trying to get it into [F-Droid.org](https://f-droid.org/)s repo directly (I can help with that). Takes a little longer, updates would be a bit delayed (usually 2..7 days) – but then you wouldn't need to provide any APK as F-Droid would build from your sources and sign it with their key. Looks like your app would meet their inclusion criteria. Just let me know if you'd be fine with that approach, and I'd see to get it started.

**Comment by manimaul** [comment]
@IzzySoft - that sounds reasonable. see #21
