### ISSUE TITLE
Alt Repo Signing Config

### ISSUE THREAD

**Issue by manimaul** [manimaul/mxtide-android#21]
Add gpg symmetric encrypted android keystore to the repo specifically for alternative distribution sources and Github Action APK artifacts.

This will NOT be the Google Play keystore even though it is encrypted. 

The alternative keystore should be used to sign universal APK artifact that is built on version tags.

**Comment by IzzySoft** [comment]
Great, thanks! Remember that for F-Droid.org (the "main repo"), no signing stuff is required from your end (we'd just need to [open a RFP](https://gitlab.com/fdroid/rfp/issues) – when accepted and picked up, F-Droid cares for building and signing).

Signed APKs would just be required for [my repo](https://apt.izzysoft.de/fdroid) – as there the updater just pulls the APK from its corresponding tag.

**Comment by manimaul** [comment]
All tagged release APKs after https://github.com/manimaul/mxtide-android/releases/tag/4.1-vcx-SNAPSHOT will produced a signed apk (using an alternate keystore than the official packages on Google Play).
